// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'input_css': string;
  'login': string;
  'login_div': string;
  'login_text': string;
  'logo': string;
  'main': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
