// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chart': string;
  'head': string;
  'label': string;
  'num': string;
  'num_div': string;
  'title': string;
  'warnModal': string;
  'warnPng': string;
  'warn_div': string;
}
export const cssExports: CssExports;
export default cssExports;
