// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ava': string;
  'content': string;
  'head': string;
  'layout': string;
  'main': string;
  'name': string;
  'outImg': string;
  'sideBar': string;
  'tab': string;
  'tabClick': string;
}
export const cssExports: CssExports;
export default cssExports;
